### ISSUE TITLE
HEAROutlineInformationModel2011-02-17.png‎ is missing

### ISSUE THREAD

**Issue by ds10** [Cetis/hear#1]
can't find it in my old backups either, the page exisits but the image is missing. Is anybody aware of what this image was or where it might be located?

**Comment by scottbw** [comment]
Found it!

HEAROutlineInformationModel2011-02-17
![hearoutlineinformationmodel2011-02-17](https://cloud.githubusercontent.com/assets/443092/13077056/6d429dfc-d4ae-11e5-8523-6601b71cdcb9.png)

**Comment by ds10** [comment]
added to images, linked from document
