### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by ds10** [Cetis/hear#6]
From @asimong on xcri repo

On the HEAR index page, there are several dead links to documents on alanpaull.co.uk. We have the original materials for several of these: need to host them on our servers somewhere and link to these versions when available.

For all linked resources, where no version is able to be found, or there is no version we are permitted to host and make public, delete the link.

**Comment by asimong** [comment]
Alan and I have intended to delete all these references. Just needs checking.

**Comment by ds10** [comment]
checked - looks fine
